/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ferramentateste;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luan
 */
public class MainScreen extends javax.swing.JFrame {
    
    ComparacaoTXT compTxt = new ComparacaoTXT();

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOpenOBJ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtWait = new javax.swing.JLabel();
        btnOrdenarTxt = new javax.swing.JButton();
        btnSelectOne = new javax.swing.JButton();
        btnSelectTwo = new javax.swing.JButton();
        btnCompare = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnOpenOBJ.setText("Abrir Arquivo OBJ");
        btnOpenOBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenOBJActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenOBJ);
        btnOpenOBJ.setBounds(180, 70, 150, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Abra o arquivo OBJ para exportar todos os elementos ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(144, 5, 433, 25);

        txtWait.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtWait.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtWait);
        txtWait.setBounds(290, 110, 120, 30);

        btnOrdenarTxt.setText("Ordenar TXT");
        btnOrdenarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarTxtActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenarTxt);
        btnOrdenarTxt.setBounds(370, 70, 120, 30);

        btnSelectOne.setText("Selecione primeiro arquivo");
        btnSelectOne.setMinimumSize(null);
        btnSelectOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectOneActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelectOne);
        btnSelectOne.setBounds(140, 190, 200, 30);

        btnSelectTwo.setText("Selecione segundo arquivo");
        btnSelectTwo.setMaximumSize(new java.awt.Dimension(171, 23));
        btnSelectTwo.setMinimumSize(null);
        btnSelectTwo.setPreferredSize(new java.awt.Dimension(171, 23));
        btnSelectTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectTwoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelectTwo);
        btnSelectTwo.setBounds(400, 190, 200, 30);

        btnCompare.setText("Compare");
        btnCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompareActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompare);
        btnCompare.setBounds(310, 240, 110, 30);

        jScrollPane1.setViewportView(txtArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 310, 400, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(755, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenOBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenOBJActionPerformed
        txtWait.setText("Aguarde");
        long startTime = System.nanoTime();
        OpenOBJFile obj = new OpenOBJFile();
        try {
            
           /* obj.exportVertices();
            obj.exportVerticesTexturizados();
            obj.exportVerticesNormais();
            obj.exportFaces();*/
           obj.exportElements();
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        long endTime = System.nanoTime();
        countTime(startTime, endTime, "Separacao dos Elementos");
        txtWait.setText("Pronto");
        
        
        
    }//GEN-LAST:event_btnOpenOBJActionPerformed

    private void btnOrdenarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarTxtActionPerformed
        long startTime = System.nanoTime();
        txtWait.setText("Aguarde");
        try {
            
            OrdenarTxt obj = new OrdenarTxt();
            obj.AbreOBJFile();
            obj.Ordenacao();
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        long endTime = System.nanoTime();
        countTime(startTime, endTime, "Ordenacao");
        
       txtWait.setText("Pronto");
         
    }//GEN-LAST:event_btnOrdenarTxtActionPerformed

    private void btnSelectOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectOneActionPerformed
        try {
            compTxt.selectFileOne();
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectOneActionPerformed

    private void btnSelectTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectTwoActionPerformed
        try {
            compTxt.selectFileTwo();
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectTwoActionPerformed

    private void btnCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompareActionPerformed
        long startTime = System.nanoTime();
        txtWait.setText("Aguarde");
        ArrayList<String> equals = compTxt.equalsLine();
        long endTime = System.nanoTime();
        countTime(startTime, endTime, "Comparacao");
        StringBuilder sb = new StringBuilder();
            for (String item : equals) {
                sb.append(item).append("\n");
            }
        String content = sb.toString();

        txtWait.setText("Pronto");    
        txtArea.setText(content);
        
    }//GEN-LAST:event_btnCompareActionPerformed

    public void countTime(long startTime, long endTime, String operacao){
        long timeElapsed = endTime - startTime;
        long milisegundos = timeElapsed / 1000000;
        
        
        long segundos = ( milisegundos / 1000 ) % 60;  
        long minutos  = ( milisegundos / 60000 ) % 60;     // 60000    = 60 * 1000
        long horas    = ( milisegundos / 3600000 ) % 24;   // 3600000  = 60 * 60 * 1000
        System.out.println(operacao+" terminou com sucesso em: "+horas+"H"+ minutos+"min"+segundos+"s" );
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompare;
    private javax.swing.JButton btnOpenOBJ;
    private javax.swing.JButton btnOrdenarTxt;
    private javax.swing.JButton btnSelectOne;
    private javax.swing.JButton btnSelectTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtArea;
    private javax.swing.JLabel txtWait;
    // End of variables declaration//GEN-END:variables
}
